version: "3.8"
services:
  user:
    image: rookie97/eeum-user:latest
    container_name: user
    ports:
      - "8081:9000"

  posts:
    image: rookie97/eeum-posts:latest
    container_name: posts
    ports:
      - "8082:9001"

  comment:
    image: rookie97/eeum-comment:latest
    container_name: comment
    ports:
      - "8083:9002"

  posts-read:
    image: rookie97/eeum-posts-read:latest
    container_name: posts-read
    ports:
      - "8084:9003"

  like:
    image: rookie97/eeum-like:latest
    container_name: like
    ports:
      - "8085:9004"

#  view:
#    image: rookie97/eeum-view:latest
#    container_name: view
#    ports:
#      - "8086:9005"