server {
    listen 80;
    server_name eeum.site;

    # dev 환경 (예: 포트 8081)
    location /dev/ {
        limit_req zone=dev_limit burst=50 nodelay;
    limit_req_status 429;
    proxy_pass http://dev_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite ^/dev(/.*)$ $1 break;
    }

    # prod 환경 (예: 포트 8080)
    location /prod/ {
    limit_req zone=prod_limit burst=20 nodelay;
    limit_req_status 429;
        proxy_pass http://prod_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite ^/prod(/.*)$ $1 break;
    }

    # 기본 경로는 prod로 연결
    location / {
    limit_req zone=prod_limit burst=20 nodelay;
    limit_req_status 429;
        proxy_pass http://prod_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 443 ssl http2;
    server_name eeum.site;

    ssl_certificate     /etc/letsencrypt/live/eeum.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eeum.site/privkey.pem;

    location /dev/ {
        limit_req zone=dev_limit burst=50 nodelay;
        limit_req_status 429;
    proxy_pass http://dev_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite ^/dev(/.*)$ $1 break;
    }

    location /prod/ {
    limit_req zone=prod_limit burst=20 nodelay;
        limit_req_status 429;
        proxy_pass http://prod_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite ^/prod(/.*)$ $1 break;
    }

    location / {
    limit_req zone=prod_limit burst=20 nodelay;
        limit_req_status 429;
        proxy_pass http://prod_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
