name: Development Server - CI/CD for EEUM

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Create application.yml
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_DEV_YML }}" > src/main/resources/application-dev.yml

      - name: Build module
        run: ./gradlew clean build

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eeum:dev .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/eeum

  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Pull latest images
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/eeum

      - name: Stop and remove containers
        run: docker compose down || true

      - name: Start containers with new images
        run: docker compose -f ${{ github.workspace }}/docker-compose-dev.yml up -d

      - name: Remove dangling images
        run: docker system prune -f